server:
  port: 7090 # 端口

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:postgresql://localhost:5432/GxPerformance?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 1
      maxActive: 2
      # 配置获取连接等待超时的时间(毫秒)
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #网络url统计
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,"
      #druid管理ui
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow:
        deny: 192.168.0.1
        login-username: admin
        login-password: admin
        reset-enable: false
      filter:
        stat:
          slow-sql-millis: 1000 #设置所有超过1000行的查询都是慢查询
          logSlowSql: true
          enabled: true
        wall: #开启防火墙的功能
          enabled: true
          config:
            drop-table-allow: false
  application:
    name: service-polygon # 应用名称(集群下相同)
#  profiles:
#    active: prod

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

info:
  app.name: service-provider-app
  company.name: www.xxx.com
  build.artifactId: service-provider
  build.version: 1.0-SNAPSHOT

geoserver:
  url: http://6.19.22.108:28080/geoserver/
  username: admin
  password: geoserver
  shpworkspace: shp
  imageworkspace: image
  
password:'{cipher}9a5ef317f7228340d9e0c8baf39e67e6d5937bd5b6132c285b5770494c9cefd0'
  
